language: node_js
node_js:
  - 8
addons:
  chrome: stable
before_script:
  - npm run bower-install
  - ./copy_dependencies.sh
script:
  - npm run test-chrome-single-run-no-sandbox
deploy:
  - provider: script
    script: ./create_zip_for_upload.sh && npm run release-beta
    on:
      branch: release-beta
      tags: true