language: node_js
node_js:
- 8
addons:
  chrome: stable
before_script:
- sudo apt-get install -y jq
- npm run bower-install
- "./copy_dependencies.sh"
script:
- npm run test-chrome-single-run-no-sandbox
after_success:
- source ./check_should_deploy.sh
before_deploy:
- git tag $NEW_VERSION
deploy:
  skip_cleanup: true
  - provider: releases
    api_key:
      secure: $GITHUB_API_KEY
    file: "./build_output/output.zip"
    on:
      branch: master
      condition: $NEW_VERSION
  - provider: script
    script: npm run release
    on:
      branch: master
      condition: $NEW_VERSION